### ISSUE TITLE
SCANR should take a length input instead of encoder ticks input

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/TigerASI#51]
Currently ```scanr``` takes as input an argument ```pulse_interval_enc_ticks```. There is a bit of mental overhead here, such that the user needs to know what length is reprsented by an encoder tick.

This is available in TigerASI via the command ```get_encoder_ticks_per_mm```.

Proposed that within ```scanr``` we instead change to ```pulse_interval_um```. Requires that:

1.  We ask ```scan``` what the fast axis id is (the one which will be scanned).
2. We internally call ```get_encoder_ticks_per_mm``` for this axis.
3. We use the output to convert the desired pulse interval rounded to a certain number of encoder ticks.
4. We then feed in this encoder ticks to the ```Z``` argument of ```SCANR```.

**Comment by Poofjunior** [comment]
Done! It's now in the main branch.
